### ISSUE TITLE
Computing frequency

### ISSUE THREAD

**Issue by zubinkadva** [m00nlight/hackerrank#1]
Hi. Based on your code, I need to find frequency of a value in a list. Similar to how you are finding LCM. I have modified your code to compute the frequency. But not getting the desired results. Can you please take a look. Many thanks.

[Frequent Values](http://pastebin.com/Mj94xHnz)

**Comment by m00nlight** [comment]
Hi @zubinkadva , Sorry but I don't get your point.  Why don't you go over the list and build a `Map Key Int` structure to do the lookup. Why do you need to use Segment Tree to do it?  Is there any special reason to do so?  

I think use a `Map Key Int` structure to do it in Haskell will make sure that all operations are in O(log n) complexity for updating, inserting and deleting etc. 

If you can make the question statement more clear I would like to help.  

Thanks

**Comment by zubinkadva** [comment]
Thanks for replying. My requirement is to use a `SegmentTree`.  Please help me.

**Comment by zubinkadva** [comment]
Any thoughts sir??

**Comment by m00nlight** [comment]
@zubinkadva  Sorry for reply late. If that is the case, could you please give some more details about you problem ?  Or if you could give some concrete example(like input and output) would be great. Since it is not clear to me what you problem actually is.
